# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./deployment/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=speeddate
  app:
    image: speeddate
    build: .
    ports:
      - 3000:3000
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080