[logging]
level = "info"
format = "json"

[http_server]
host = "localhost"
port = "3000"
jwt_expiration = "5m"
jwt_public_key = "./public.pem"
jwt_public_key = "./private.pem"

[database]
host = "postgres"
port = "5432"
user = "postgres"
password = "speeddate"